# Generated by Django 3.2.9 on 2021-11-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalInfo',
            fields=[
                ('project_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=80)),
                ('responsible_institution', models.CharField(max_length=120)),
                ('total_target_number', models.IntegerField(null=True)),
                ('research_duration', models.CharField(max_length=10, null=True)),
                ('research_type', models.CharField(max_length=10)),
                ('clinical_trial_stage', models.CharField(max_length=20, null=True)),
                ('research_scope', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinical_infos',
            },
        ),
    ]
